apiVersion: v1
kind: Pod
metadata:
  name: test-privileged
  labels:
    app: nginx
    test-type: security
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    securityContext:
      privileged: true  # Security issue: privileged container
      runAsNonRoot: false  # Security issue: running as root
    resources: {}  # Security issue: no resource limits