apiVersion: v1
kind: Pod
metadata:
  name: test-privileged
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    securityContext:
      privileged: true  # Insecure configuration
    resources: {}       # Missing limits